<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

	    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>

        <PackageId>riri.yamlscans</PackageId>

        <Version>1.0.2</Version>
        <Authors>Rirurin</Authors>

        <Description>A library for reading Scan YAML formatted files, intended for Reloaded-II mods</Description>
        <PackageIconUrl>https://avatars1.githubusercontent.com/u/45473408</PackageIconUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NCalcSync" Version="6.3.1" />
      <PackageReference Include="YamlDotNet" Version="18.0.0" />
    </ItemGroup>

</Project>
